import json

ENV_OTHER_METADATA = json.load(open(f"assets/env_other_metadata.json", 'r'))

old_scene_to_new_scene = {
    "modules/indoor_scenes/scenes/restaurant-0.json" : ('food', 0),
    "modules/indoor_scenes/scenes/restaurant-1.json" : ('food', 1),
    "modules/indoor_scenes/scenes/restaurant-2.json" : ('food', 0),
    "modules/indoor_scenes/scenes/restaurant-3.json" : ('food', 1),
    "modules/indoor_scenes/scenes/office-1.json" : ('office', 0),
    "modules/indoor_scenes/scenes/office-0.json" : ('office', 1),
    "modules/indoor_scenes/scenes/office-2.json" : ('office', 0),
    "modules/indoor_scenes/scenes/office-3.json" : ('office', 1),
    "modules/indoor_scenes/scenes/office-4.json" : ('office', 0),
    "modules/indoor_scenes/scenes/office-5.json" : ('office', 1),
    "modules/indoor_scenes/scenes/bookstore-0.json" : ('entertainment', 0),
    "modules/indoor_scenes/scenes/gamestore-0.json" : ('entertainment', 0),
    "modules/indoor_scenes/scenes/hospital-0.json" : ('hospital', 0)
}

LIGHTS = [{
                'type': 'directional',
                'dir': (0, -1, -1),
                'color': (1.0, 1.0, 1.0),
                'intensity': 1.0,
            },
            {
                'type': 'directional',
                'dir': (0, 1, -1),
                'color': (1.0, 1.0, 1.0),
                'intensity': 1.0,
            },
            {
                'type': 'directional',
                'dir': (1, 0, -1),
                'color': (1.0, 1.0, 1.0),
                'intensity': 1.0,
            },
            {
                'type': 'directional',
                'dir': (-1, 0, -1),
                'color': (1.0, 1.0, 1.0),
                'intensity': 1.0,
            }

            ]  # DAY
#   'intensity' : 2.5},] # NIGHT
google_map_coarse_to_types = json.load(open("assets/places_type_basic.json", 'r'))

google_map_types = [
    "accounting", "airport", "amusement_park", "aquarium", "art_gallery", "atm",
    "bakery", "bank", "bar", "beauty_salon", "bicycle_store", "book_store", 
    "bowling_alley", "bus_station", "cafe", "campground", "car_dealer", "car_rental", 
    "car_repair", "car_wash", "casino", "cemetery", "church", "city_hall", 
    "clothing_store", "convenience_store", "courthouse", "dentist", "department_store", 
    "doctor", "drugstore", "electrician", "electronics_store", "embassy", 
    "fire_station", "florist", "funeral_home", "furniture_store", "gas_station", 
    "gym", "hair_care", "hardware_store", "hindu_temple", "home_goods_store", 
    "hospital", "insurance_agency", "jewelry_store", "laundry", "lawyer", "library", 
    "light_rail_station", "liquor_store", "local_government_office", "locksmith", 
    "lodging", "meal_delivery", "meal_takeaway", "mosque", "movie_rental", 
    "movie_theater", "moving_company", "museum", "night_club", "painter", "park", 
    "parking", "pet_store", "pharmacy", "physiotherapist", "plumber", "police", 
    "post_office", "primary_school", "real_estate_agency", "restaurant", 
    "roofing_contractor", "rv_park", "school", "secondary_school", "shoe_store", 
    "shopping_mall", "spa", "stadium", "storage", "store", "subway_station", 
    "supermarket", "synagogue", "taxi_stand", "tourist_attraction", "train_station", 
    "transit_station", "travel_agency", "university", "veterinary_care", "zoo",
    "administrative_area_level_1", "administrative_area_level_2", "administrative_area_level_3",
    "administrative_area_level_4", "administrative_area_level_5", "administrative_area_level_6",
    "administrative_area_level_7", "archipelago", "colloquial_area", "continent", 
    "country", "establishment", "finance", "floor", "food", "general_contractor", 
    "geocode", "health", "intersection", "landmark", "locality", "natural_feature", 
    "neighborhood", "place_of_worship", "plus_code", "point_of_interest", "political", 
    "post_box", "postal_code", "postal_code_prefix", "postal_code_suffix", "postal_town",
    "premise", "room", "route", "street_address", "street_number", "sublocality",
    "sublocality_level_1", "sublocality_level_2", "sublocality_level_3", 
    "sublocality_level_4", "sublocality_level_5", "subpremise", "town_square"
]

google_map_type_to_coarse = {}

for coarse in google_map_coarse_to_types:
    for type in google_map_coarse_to_types[coarse]:
        google_map_type_to_coarse[type] = coarse

# google_map_type_to_coarse = {
#     "accounting": "finance",
#     "airport": "transportation",
#     "amusement_park": "entertainment",
#     "aquarium": "entertainment",
#     "art_gallery": "entertainment",
#     "atm": "finance",
#     "bakery": "retail",
#     "bank": "finance",
#     "bar": "food",
#     "beauty_salon": "retail",
#     "bicycle_store": "retail",
#     "book_store": "retail",
#     "bowling_alley": "entertainment",
#     "bus_station": "transportation",
#     "cafe": "food",
#     "campground": "accommodation",
#     "car_dealer": "transportation",
#     "car_rental": "transportation",
#     "car_repair": "transportation",
#     "car_wash": "transportation",
#     "casino": "entertainment",
#     "cemetery": "public",
#     "church": "public",
#     "city_hall": "public",
#     "clothing_store": "retail",
#     "convenience_store": "retail",
#     "courthouse": "public",
#     "dentist": "health",
#     "department_store": "retail",
#     "doctor": "health",
#     "drugstore": "health",
#     "electrician": "others",
#     "electronics_store": "retail",
#     "embassy": "public",
#     "fire_station": "public",
#     "florist": "retail",
#     "funeral_home": "public",
#     "furniture_store": "retail",
#     "gas_station": "transportation",
#     "gym": "entertainment",
#     "hair_care": "retail",
#     "hardware_store": "retail",
#     "hindu_temple": "public",
#     "home_goods_store": "retail",
#     "hospital": "health",
#     "insurance_agency": "finance",
#     "jewelry_store": "retail",
#     "laundry": "others",
#     "lawyer": "finance",
#     "library": "education",
#     "light_rail_station": "transportation",
#     "liquor_store": "retail",
#     "local_government_office": "public",
#     "locksmith": "retail",
#     "lodging": "accommodation",
#     "meal_delivery": "food",
#     "meal_takeaway": "food",
#     "mosque": "public",
#     "movie_rental": "entertainment",
#     "movie_theater": "entertainment",
#     "moving_company": "transportation",
#     "museum": "entertainment",
#     "night_club": "entertainment",
#     "painter": "others",
#     "park": "entertainment",
#     "parking": "transportation",
#     "pet_store": "retail",
#     "pharmacy": "health",
#     "physiotherapist": "health",
#     "plumber": "others",
#     "police": "public",
#     "post_office": "public",
#     "primary_school": "education",
#     "real_estate_agency": "accommodation",
#     "restaurant": "food",
#     "roofing_contractor": "others",
#     "rv_park": "accommodation",
#     "school": "education",
#     "secondary_school": "education",
#     "shoe_store": "retail",
#     "shopping_mall": "retail",
#     "spa": "health",
#     "stadium": "entertainment",
#     "storage": "others",
#     "store": "retail",
#     "subway_station": "transportation",
#     "supermarket": "retail",
#     "synagogue": "public",
#     "taxi_stand": "transportation",
#     "tourist_attraction": "entertainment",
#     "train_station": "transportation",
#     "transit_station": "transportation",
#     "travel_agency": "others",
#     "university": "education",
#     "veterinary_care": "health",
#     "zoo": "entertainment",
#     "administrative_area_level_1": "public",
#     "administrative_area_level_2": "public",
#     "administrative_area_level_3": "public",
#     "administrative_area_level_4": "public",
#     "administrative_area_level_5": "public",
#     "administrative_area_level_6": "public",
#     "administrative_area_level_7": "public",
#     "archipelago": "others",
#     "colloquial_area": "others",
#     "continent": "others",
#     "country": "others",
#     "establishment": "others",
#     "finance": "finance",
#     "floor": "others",
#     "food": "food",
#     "general_contractor": "others",
#     "geocode": "others",
#     "health": "health",
#     "intersection": "others",
#     "landmark": "others",
#     "locality": "others",
#     "natural_feature": "others",
#     "neighborhood": "others",
#     "place_of_worship": "public",
#     "plus_code": "others",
#     "point_of_interest": "others",
#     "political": "public",
#     "post_box": "public",
#     "postal_code": "others",
#     "postal_code_prefix": "others",
#     "postal_code_suffix": "others",
#     "postal_town": "public",
#     "premise": "others",
#     "room": "others",
#     "route": "others",
#     "street_address": "others",
#     "street_number": "others",
#     "sublocality": "others",
#     "sublocality_level_1": "others",
#     "sublocality_level_2": "others",
#     "sublocality_level_3": "others",
#     "sublocality_level_4": "others",
#     "sublocality_level_5": "others",
#     "subpremise": "others",
#     "town_square": "public", 
#     "student_dormitory": "accommodation",
#     "apartment": "accommodation"
# }

# coarse_types_priority = {
#     'accommodation': 5,
#     'education': 4,
#     'food': 3,
#     'entertainment': 2,
#     'retail': 1,
#     'transportation': 1,
#     'finance': 1,
#     'health': 1,
#     'public': 1,
#     'others': 1
# }

coarse_types_priority = {
    'accommodation': 5,
    'office': 4,
    'food': 3,
    'entertainment': 2,
    "stores": 1,
    'public': 1
}